apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cv0v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cv0v
    app.kubernetes.io/part-of: ci1t-830-0049-app
  name: devfile-sample-cv0v
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cv0v
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cv0v
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0049-tenant/ci1t-830-0049-app/devfile-sample-cv0v@sha256:512ab17e53d8e157e3ee6a93c654d6f0a2e92d180b7c50168cad734ff0ca21d4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
